name: Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  ENV_VARS: ${{ secrets.ENV_VARS }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Create .env file
        run: echo "$ENV_VARS" > .env

      - name: Build Docker image
        run: docker build -t book-to-kindle-bot .

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --dockerfile dockerfile --detach -y